---
- hosts: servers
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install psycopg2
      apt:
        name: python3-psycopg2
        state: present

    - name: Добавить PostgreSQL GPG key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Добавить репозиторий PostgreSQL
      apt_repository:
        repo: 'deb http://apt.postgresql.org/pub/repos/apt/ noble-pgdg main'
        state: present

    - name: Установка PostgreSQL
      apt:
        name: 'postgresql-16'
        state: present

    - name: Включить и запустить PostgreSQL
      systemd:
        name: postgresql
        enabled: yes
        state: started


